name: Check
on: push
jobs:
  lint:
    runs-on: macos-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.12'
        - name: Install dependencies
          run: |
            python3 -m pip install --upgrade pip
        - name: Run tests
          run: |
            python3 -m unittest discover